# -*- coding: utf-8 -*-
"""Q1 AI LAB TEST.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ebZz_oSuSp62EYPi-CdPvX34UwulYeza
"""

import numpy as np
import streamlit as st
import pandas as pd

# ---------------- Parameters ----------------
POP_SIZE = 300
GENE_LENGTH = 80
MAX_GEN = 50
PC = 0.9
PM = 0.01
ELITE = 2
TOUR_K = 3
SEED = 42

rng = np.random.default_rng(SEED)


# Fitness (OneMax)
def fitness(pop):
    return np.sum(pop, axis=1)


def init_population():
    return rng.integers(0, 2, size=(POP_SIZE, GENE_LENGTH))


def tournament_selection(pop, fit):
    candidates = rng.choice(len(pop), TOUR_K, replace=False)
    return pop[candidates[np.argmax(fit[candidates])]]


# Two-point crossover (changed from one-point)
def crossover(p1, p2):
    if rng.random() < PC:
        p1_idx, p2_idx = sorted(rng.integers(1, GENE_LENGTH, 2))
        c1 = np.concatenate([p1[:p1_idx], p2[p1_idx:p2_idx], p1[p2_idx:]])
        c2 = np.concatenate([p2[:p1_idx], p1[p1_idx:p2_idx], p2[p2_idx:]])
        return c1, c2
    return p1.copy(), p2.copy()


def mutation(child):
    flip = rng.random(GENE_LENGTH) < PM
    child[flip] ^= 1
    return child


def run_ga():
    population = init_population()
    history = []

    progress = st.progress(0)

    for gen in range(MAX_GEN):
        fit = fitness(population)

        history.append({
            "Generation": gen + 1,
            "Best Fitness": fit.max(),
            "Average Fitness": fit.mean()
        })

        # Elitism
        elite_idx = np.argsort(fit)[-ELITE:]
        elites = population[elite_idx]

        new_population = []

        while len(new_population) < POP_SIZE - ELITE:
            parent1 = tournament_selection(population, fit)
            parent2 = tournament_selection(population, fit)
            child1, child2 = crossover(parent1, parent2)
            new_population.append(mutation(child1))
            if len(new_population) < POP_SIZE - ELITE:
                new_population.append(mutation(child2))

        population = np.vstack([new_population, elites])
        progress.progress((gen + 1) / MAX_GEN)

    final_fit = fitness(population)
    best_index = np.argmax(final_fit)

    return pd.DataFrame(history), population[best_index], final_fit[best_index]


# ---------------- Streamlit UI ----------------
st.set_page_config(page_title="Genetic Algorithm – OneMax", layout="wide")
st.title("Genetic Algorithm (OneMax Problem)")

if st.button("Run Genetic Algorithm"):
    history, best_solution, best_fitness = run_ga()

    st.subheader("Fitness Convergence")
    st.line_chart(history.set_index("Generation"))

    st.subheader("Best Solution Found")
    st.write(f"Best Fitness: **{best_fitness} / {GENE_LENGTH}**")
    st.code("".join(best_solution.astype(str)))