# -*- coding: utf-8 -*-
"""Q2 AI LAB TEST .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_C40dKpzsp66AhPiEipSsdexkZ6-2efY
"""

# app.py
import json
from typing import List, Dict, Any, Tuple
import operator
import streamlit as st

# ----------------------------
# 1) Rule Engine
# ----------------------------
OPS = {
    "==": operator.eq,
    "!=": operator.ne,
    ">": operator.gt,
    ">=": operator.ge,
    "<": operator.lt,
    "<=": operator.le,
}

# Small changes:
# - Slight renaming of some rule titles
# - Priorities adjusted a bit
# - Default fan speed for OFF is now "AUTO"
DEFAULT_RULES: List[Dict[str, Any]] = [

    {
        "name": "Windows open → AC OFF",
        "priority": 110,
        "conditions": [
            ["windows_open", "==", True]
        ],
        "action": {
            "mode": "OFF",
            "fan_speed": "AUTO",
            "setpoint": None,
            "reason": "Cooling disabled because windows are open"
        }
    },

    {
        "name": "Empty house → Eco mode",
        "priority": 95,
        "conditions": [
            ["occupancy", "==", "EMPTY"],
            ["temperature", ">=", 24]
        ],
        "action": {
            "mode": "ECO",
            "fan_speed": "LOW",
            "setpoint": 27,
            "reason": "No occupants, energy saving activated"
        }
    },

    {
        "name": "Hot & humid while occupied",
        "priority": 85,
        "conditions": [
            ["occupancy", "==", "OCCUPIED"],
            ["temperature", ">=", 30],
            ["humidity", ">=", 70]
        ],
        "action": {
            "mode": "COOL",
            "fan_speed": "HIGH",
            "setpoint": 23,
            "reason": "High temperature and humidity detected"
        }
    },

    {
        "name": "Hot while occupied",
        "priority": 75,
        "conditions": [
            ["occupancy", "==", "OCCUPIED"],
            ["temperature", ">=", 28]
        ],
        "action": {
            "mode": "COOL",
            "fan_speed": "MEDIUM",
            "setpoint": 24,
            "reason": "High temperature detected"
        }
    },

    {
        "name": "Warm while occupied",
        "priority": 65,
        "conditions": [
            ["occupancy", "==", "OCCUPIED"],
            ["temperature", ">=", 26],
            ["temperature", "<", 28]
        ],
        "action": {
            "mode": "COOL",
            "fan_speed": "LOW",
            "setpoint": 25,
            "reason": "Moderately warm environment"
        }
    },

    {
        "name": "Night comfort mode",
        "priority": 80,
        "conditions": [
            ["occupancy", "==", "OCCUPIED"],
            ["time_of_day", "==", "NIGHT"],
            ["temperature", ">=", 26]
        ],
        "action": {
            "mode": "SLEEP",
            "fan_speed": "LOW",
            "setpoint": 26,
            "reason": "Night-time comfort optimization"
        }
    },

    {
        "name": "Too cold → system OFF",
        "priority": 90,
        "conditions": [
            ["temperature", "<=", 22]
        ],
        "action": {
            "mode": "OFF",
            "fan_speed": "AUTO",
            "setpoint": None,
            "reason": "Temperature already low"
        }
    }
]


def evaluate_condition(facts: Dict[str, Any], cond: List[Any]) -> bool:
    field, op, value = cond
    if field not in facts or op not in OPS:
        return False
    return OPS[op](facts[field], value)


def rule_matches(facts: Dict[str, Any], rule: Dict[str, Any]) -> bool:
    # clearer variable name
    return all(evaluate_condition(facts, condition) for condition in rule["conditions"])


def run_rules(
    facts: Dict[str, Any],
    rules: List[Dict[str, Any]]
) -> Tuple[Dict[str, Any], List[Dict[str, Any]]]:

    matched_rules = [r for r in rules if rule_matches(facts, r)]

    if not matched_rules:
        return {
            "mode": "OFF",
            "fan_speed": "AUTO",
            "setpoint": None,
            "reason": "No rule satisfied"
        }, []

    # Sort by priority (highest first)
    matched_rules.sort(key=lambda r: r["priority"], reverse=True)
    return matched_rules[0]["action"], matched_rules


# ----------------------------
# 2) Streamlit UI
# ----------------------------
st.set_page_config(page_title="Smart AC Rule-Based System", layout="wide")
st.title("Smart Air Conditioner – Rule-Based Controller")

with st.sidebar:
    st.header("Home Conditions")

    temperature = st.number_input("Temperature (°C)", value=23, step=1)
    humidity = st.number_input("Humidity (%)", value=50, step=1)
    occupancy = st.selectbox("Occupancy Status", ["OCCUPIED", "EMPTY"])
    time_of_day = st.radio("Time of Day", ["DAY", "NIGHT"])
    windows_open = st.checkbox("Windows are open", value=False)

    run = st.button("Run Rules", type="primary")

facts = {
    "temperature": temperature,
    "humidity": humidity,
    "occupancy": occupancy,
    "time_of_day": time_of_day,
    "windows_open": windows_open
}

st.subheader("Current Facts")
st.json(facts)

if run:
    action, fired_rules = run_rules(facts, DEFAULT_RULES)

    st.subheader("Selected AC Action")
    st.info(
        f"""
        **Mode:** {action['mode']}
        **Fan Speed:** {action['fan_speed']}
        **Setpoint:** {action['setpoint']}
        **Reason:** {action['reason']}
        """
    )

    st.subheader("Rules That Matched (sorted by priority)")
    if fired_rules:
        for r in fired_rules:
            st.write(f"🔹 **{r['name']}** → priority `{r['priority']}`")
    else:
        st.write("No rules matched the current conditions.")